# GitHub Sponsors
github: [therif, blitzh]

# Other supported platforms
patreon: therif
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
lfx_crowdfunding:

# Custom sponsorship links
# custom:
  # - https://paypal.me/galonair
  # - https://saweria.co/therif
  # - https://sociabuzz.com/therif/tribe

custom: ['https://paypal.me/galonair', 'https://saweria.co/therif', 'https://sociabuzz.com/therif/tribe']



